controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

welcome:
    path: /
    controller: Symfony\Bundle\WelcomePageBundle\Controller\WelcomeController::index