#index:
#    path: /
#    controller: App\Controller\DefaultController::index

profile:
    path: /profile
    controller: App\Controller\ProfileController::profile

change_password:
    path: /change-password
    controller: App\Controller\ChangePasswordController::changePassword
