parameters:
    hubspot_token: '%env(HUBSPOT_PRIVATE_APP_TOKEN)%'
    hubspot_secret: '%env(HUBSPOT_APP_SECRET)%'
    profiles_directory: '%kernel.project_dir%/public/uploads/profiles'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Repository\:
        resource: '../src/Repository'
        public: true

    # HubspotWebhookController - explicit scalar injection
    App\Controller\HubspotWebhookController:
        public: true
        autowire: true          # ✅ must be true
        autoconfigure: true
        arguments:
            $client: '@http_client'
            $hubspotToken: '%hubspot_token%'
            $hubspotSecret: '%hubspot_secret%'
        tags: ['controller.service_arguments']

    # All non-admin controllers (excluding HubspotWebhookController)
    App\Controller\:
        resource: '../src/Controller/'
        exclude:
            - '../src/Controller/HubspotWebhookController.php'
            - '../src/Controller/Admin/'
        public: true
        tags: ['controller.service_arguments']

    # Explicitly register each admin controller
    App\Controller\Admin\UserController:
        public: true
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']

    App\Security\LoginSuccessHandler:
        public: true
        autowire: true
        autoconfigure: true
